apiVersion: v1
kind: Pod
metadata:
  annotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.11.2-4
      workingDir: /home/jenkins/agent
      env:
        - name: JENKINS_URL
          value: "http://jenkins.jenkins.svc.cluster.local:8080/"
      resources:
        requests:
          cpu: 200m
          memory: 350Mi
          ephemeral-storage: 150Mi
        limits:
          cpu: 512m
          memory: 512Mi
          ephemeral-storage: 200Mi
      securityContext:
        privileged: true
    - name: shell
      image: public.ecr.aws/a2q7i5i2/sl-jenkins-all-in:latest
      command:
        - sleep
      args:
        - infinity
      resources:
        requests:
          memory: 5000Mi
          cpu: 2
          ephemeral-storage: 2000Mi
        limits:
          memory: 10000Mi
          cpu: 6
          ephemeral-storage: 10000Mi
