apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.11.2-4
      workingDir: /home/jenkins/agent
      env:
        - name: JENKINS_URL
          value: "http://jenkins.jenkins.svc.cluster.local:8080/"
      resources:
        requests:
          cpu: 200m
          memory: 350Mi
          ephemeral-storage: 150Mi
        limits:
          cpu: 512m
          memory: 512Mi
          ephemeral-storage: 200Mi
      securityContext:
        privileged: true
    - name: shell
      image: public.ecr.aws/a2q7i5i2/sl-jenkins-base-ci:latest
      command:
        - sleep
      args:
        - infinity
      resources:
        requests:
          memory: 300Mi
          cpu: 0.5
          ephemeral-storage: 1000Mi
        limits:
          memory: 500Mi
          cpu: 1.0
          ephemeral-storage: 2000Mi
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 1000
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - infinity
      resources:
        requests:
          memory: 400Mi
          cpu: 0.5
          ephemeral-storage: 1000Mi
        limits:
          memory: 700Mi
          cpu: 1.5
          ephemeral-storage: 1000Mi
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      projected:
        sources:
          - secret:
              name: docker-cfg
              items:
                - key: .dockerconfigjson
                  path: config.json
    - name: postgresql-data
      emptyDir: {}
